<?php

namespace App\Services\WhatsApp;

use App\Exceptions\MetaApiException;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;
use Throwable;

class MetaTokenExchangeService
{
    public function __construct(
        private readonly ?string $appId = null,
        private readonly ?string $appSecret = null,
        private readonly string $graphApiVersion = 'v23.0',
    ) {}

    /**
     * Exchange the Embedded Signup code for the customer-scoped Business
     * Integration System User token generated by Facebook Login for Business.
     *
     * @return array{access_token: string, system_user_id: null, permanent: true, business_id: string, waba_id: string, phone_number_id: string}
     *
     * @throws MetaApiException if the code or selected assets cannot be validated
     */
    public function exchangeCodeForPermanentToken(
        string $code,
        string $wabaId,
        string $businessId = '',
        string $phoneNumberId = '',
    ): array {
        $appId = $this->appId ?? (string) config('services.meta.app_id');
        $appSecret = $this->appSecret ?? (string) config('services.meta.app_secret');

        if (! $appId || ! $appSecret) {
            throw new MetaApiException('Meta app credentials not configured (check META_APP_ID / META_APP_SECRET).');
        }

        // redirect_uri MUST be empty for Embedded Signup flows.
        $step1 = Http::timeout(15)->get("https://graph.facebook.com/{$this->graphApiVersion}/oauth/access_token", [
            'client_id' => $appId,
            'client_secret' => $appSecret,
            'code' => $code,
            'redirect_uri' => '',
        ]);

        if (! $step1->successful()) {
            Log::error('meta.token_exchange.code_exchange_failed', [
                'status' => $step1->status(),
                'error_type' => $step1->json('error.type'),
            ]);
            throw new MetaApiException('Embedded Signup code exchange failed.');
        }

        $businessToken = (string) $step1->json('access_token', '');
        if (! $businessToken) {
            throw new MetaApiException('Meta did not return an access_token.');
        }

        $phoneNumberId = $this->resolvePhoneNumberId($wabaId, $businessToken, $phoneNumberId);
        $businessId = $this->resolveBusinessId($wabaId, $businessToken, $businessId);

        return [
            'access_token' => $businessToken,
            'system_user_id' => null,
            'permanent' => true,
            'business_id' => $businessId,
            'waba_id' => $wabaId,
            'phone_number_id' => $phoneNumberId,
        ];
    }

    /**
     * Subscribe the WABA to this app so Meta starts delivering webhook events.
     * Must be called once after a new Meta instance is created.
     */
    public function subscribeWaba(string $wabaId, string $accessToken): bool
    {
        try {
            $response = Http::withToken($accessToken)
                ->timeout(15)
                ->post("https://graph.facebook.com/{$this->graphApiVersion}/{$wabaId}/subscribed_apps");
        } catch (Throwable $e) {
            Log::warning('meta.token_exchange.subscribe_waba_exception', [
                'waba_id' => $wabaId,
                'error' => $e->getMessage(),
            ]);

            return false;
        }

        if (! $response->successful()) {
            Log::warning('meta.token_exchange.subscribe_waba_failed', [
                'waba_id' => $wabaId,
                'status' => $response->status(),
                'error' => $response->json('error.message'),
            ]);

            return false;
        }

        Log::info('meta.token_exchange.waba_subscribed', ['waba_id' => $wabaId]);

        return true;
    }

    /**
     * Register phone number on the Cloud API (required for modes A/B, skip for mode C coexistence).
     */
    public function registerPhoneNumber(string $phoneNumberId, string $accessToken, string $pin): bool
    {
        try {
            $response = Http::withToken($accessToken)->timeout(15)->post(
                "https://graph.facebook.com/{$this->graphApiVersion}/{$phoneNumberId}/register",
                ['messaging_product' => 'whatsapp', 'pin' => $pin]
            );
        } catch (Throwable $e) {
            Log::warning('meta.token_exchange.register_phone_exception', [
                'phone_number_id' => $phoneNumberId,
                'error' => $e->getMessage(),
            ]);

            return false;
        }

        if (! $response->successful()) {
            Log::warning('meta.token_exchange.register_phone_failed', [
                'phone_number_id' => $phoneNumberId,
                'status' => $response->status(),
            ]);

            return false;
        }

        return true;
    }

    public function isCoexistencePhone(string $phoneNumberId, string $accessToken): bool
    {
        $response = Http::withToken($accessToken)
            ->timeout(15)
            ->get("https://graph.facebook.com/{$this->graphApiVersion}/{$phoneNumberId}", [
                'fields' => 'is_on_biz_app,platform_type',
            ]);

        if (! $response->successful()) {
            Log::warning('meta.token_exchange.coexistence_status_failed', [
                'phone_number_id' => $phoneNumberId,
                'status' => $response->status(),
            ]);

            return false;
        }

        return $response->json('is_on_biz_app') === true
            && $response->json('platform_type') === 'CLOUD_API';
    }

    public function requestAppDataSync(string $phoneNumberId, string $accessToken, string $syncType): bool
    {
        if (! in_array($syncType, ['smb_app_state_sync', 'history'], true)) {
            throw new \InvalidArgumentException('Unsupported WhatsApp Business app sync type.');
        }

        try {
            $response = Http::withToken($accessToken)->timeout(15)->post(
                "https://graph.facebook.com/{$this->graphApiVersion}/{$phoneNumberId}/smb_app_data",
                [
                    'messaging_product' => 'whatsapp',
                    'sync_type' => $syncType,
                ]
            );
        } catch (Throwable $e) {
            Log::warning('meta.coexistence.sync_request_exception', [
                'phone_number_id' => $phoneNumberId,
                'sync_type' => $syncType,
                'error' => $e->getMessage(),
            ]);

            return false;
        }

        if (! $response->successful()) {
            Log::warning('meta.coexistence.sync_request_failed', [
                'phone_number_id' => $phoneNumberId,
                'sync_type' => $syncType,
                'status' => $response->status(),
                'error' => $response->json('error.message'),
            ]);

            return false;
        }

        return true;
    }

    private function resolveBusinessId(string $wabaId, string $businessToken, string $requestedBusinessId): string
    {
        $response = Http::withToken($businessToken)
            ->timeout(15)
            ->get("https://graph.facebook.com/{$this->graphApiVersion}/{$wabaId}", [
                'fields' => 'owner_business_info',
            ]);

        $ownerBusinessId = $response->successful()
            ? (string) $response->json('owner_business_info.id', '')
            : '';

        if ($ownerBusinessId !== '' && $requestedBusinessId !== '' && $ownerBusinessId !== $requestedBusinessId) {
            throw new MetaApiException('A conta do WhatsApp não pertence ao portfólio empresarial retornado pela Meta.');
        }

        $businessId = $requestedBusinessId !== '' ? $requestedBusinessId : $ownerBusinessId;

        if ($businessId === '') {
            throw new MetaApiException('Não foi possível identificar o portfólio empresarial da conta do WhatsApp.');
        }

        return $businessId;
    }

    private function resolvePhoneNumberId(string $wabaId, string $businessToken, string $requestedPhoneNumberId): string
    {
        $response = Http::withToken($businessToken)->timeout(15)->get(
            "https://graph.facebook.com/{$this->graphApiVersion}/{$wabaId}/phone_numbers",
            ['fields' => 'id,display_phone_number,status']
        );

        if (! $response->successful()) {
            throw new MetaApiException('Não foi possível consultar os números da conta do WhatsApp selecionada.');
        }

        $phones = (array) $response->json('data', []);
        $phoneIds = collect($phones)
            ->pluck('id')
            ->filter(fn (mixed $id): bool => is_scalar($id) && (string) $id !== '')
            ->map(fn (mixed $id): string => (string) $id)
            ->values();

        if ($requestedPhoneNumberId !== '') {
            if (! $phoneIds->contains($requestedPhoneNumberId)) {
                throw new MetaApiException('O número retornado não pertence à conta do WhatsApp selecionada.');
            }

            return $requestedPhoneNumberId;
        }

        if ($phoneIds->count() !== 1) {
            throw new MetaApiException('A Meta não informou qual número foi selecionado. Refaça a vinculação escolhendo um número específico.');
        }

        return $phoneIds->first();
    }
}
